name: Deploy to Production

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: SSH Remote
        uses: fifsky/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command: |
            # Navigate to the project directory
            cd /var/www/e-perpustakaan.ikhbarnuri.dev

            # Put the Laravel application into maintenance mode
            php artisan down

            # Discard any local changes and reset the working directory to the latest commit
            git reset --hard

            # Pull the latest code from the main branch of the Git repository
            git pull origin main

            # Install PHP dependencies defined in composer.json
            composer install --optimize-autoloader

            # Install JavaScript dependencies defined in package.json
            npm install

            # Build the project (typically for production)
            npm run build

            # Delete node_modules folder to clean up unnecessary dev dependencies after build
            rm -rf node_modules

            # Cache all Blade icons to improve performance
            php artisan migrate

            # Cache all Blade icons to improve performance
            php artisan filament:optimize

            # Bring the Laravel application back up (exit maintenance mode)
            php artisan up
